name: nqurack
description: Intelligent file organizer CLI tool
version: 1.0.0

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
